### PR TITLE
file structure yo

### PR DESCRIPTION
**Pull request by klboyd**
# Description
It's the file structure, yo.

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# Testing Instructions
It's the file structure, yo.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works
- [ ] My functions have doc strings

### CODE REVIEW

**Review by laurenriddle — DISMISSED** [review]
🐬+ 🍓(crunchberries) = 😌

**Review by laurenriddle — DISMISSED** [review]
🐝's look good! 🍯

**Review by RyanCrowleyCode — DISMISSED** [review]
You turned that Nay Nay Goose into a Yay Yay goose.

**Review by RyanCrowleyCode — APPROVED** [review]
Yay Yay Goose 2: the return

**Review by laurenriddle — APPROVED** [review]
💥

**Review by treysuiter — APPROVED** [review]
👉 yes!

**Pull request merged**
