### PR TITLE
Rc 10k price

### PR DESCRIPTION
**Pull request by RyanCrowleyCode**
# Description

For ticket 24, the maximum price a user can sell an item for is $10,000.00. I also added a few extra checks on the form, below.

When creating a product to sell:
- A user must complete all fields
- A user can not add a product to sell that has a negative quantity
- A user cannot sell a product for $0 or less
- A user cannot sell a product for more than $10,000
- If a user tries to sell a quantity that isn't an integer, the quantity saved will be an integer

Fixes #24

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

Add and Commit your current branch
`git checkout master`
`git fetch --all`
`git checkout rc-10k-price`
Go to http://localhost:3000/product/new

Try to add a new product and confirm the following:
- A user must complete all fields
- A user can not add a product to sell that has a negative quantity
- A user cannot sell a product for $0 or less
- A user cannot sell a product for more than $10,000
- If a user tries to sell a quantity that isn't an integer, the quantity saved will be an integer

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works
- [x] My functions have doc strings

### CODE REVIEW

**Review by laurenriddle — DISMISSED** [review]
🏝

**Review by laurenriddle — DISMISSED** [review]
🚢

**Review by treysuiter — APPROVED** [review]
do the thang

**Review by laurenriddle — APPROVED** [review]
🗻

**Pull request merged**
